ci:
  autoupdate_commit_msg: "MAINT: update pip constraints and pre-commit"
  autoupdate_schedule: quarterly # already done by requirements-cron.yml
  skip:
    - mypy
    - pyright

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/ComPWA/policy
    rev: 0.4.0
    hooks:
      - id: check-dev-files
        args:
          - --doc-apt-packages=graphviz
          - --github-pages
          - --no-prettierrc
          - --pin-requirements=bimonthly
          - --repo-name=ampform-dpd
          - --repo-title=AmpForm-DPD
      - id: colab-toc-visible
      - id: remove-empty-tags

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        args:
          - --drop-empty-cells
          - --extra-keys
          - |
            cell.attachments
            cell.metadata.code_folding
            cell.metadata.editable
            cell.metadata.id
            cell.metadata.pycharm
            cell.metadata.slideshow
            cell.metadata.user_expressions
            metadata.celltoolbar
            metadata.colab.name
            metadata.colab.provenance
            metadata.interpreter
            metadata.notify_time
            metadata.toc
            metadata.toc-autonumbering
            metadata.toc-showcode
            metadata.toc-showmarkdowntxt
            metadata.toc-showtags
            metadata.varInspector
            metadata.vscode

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/ComPWA/prettier-pre-commit
    rev: v3.3.3
    hooks:
      - id: prettier

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort
        args:
          - --in-place

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.13.3
    hooks:
      - id: cspell

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.0.3
    hooks:
      - id: editorconfig-checker
        name: editorconfig
        alias: ec
        exclude: >-
          (?x)^(
            .*\.py
          )$

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        require_serial: true
        types:
          - python

  - repo: https://github.com/ComPWA/mirrors-pyright
    rev: v1.1.379
    hooks:
      - id: pyright
