codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: 50%
        threshold: 1%
        base: auto
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: 0
        threshold: 5%
        base: auto
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
    changes: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: false
