name: ampform-dpd
channels:
  - defaults
dependencies:
  - graphviz
  - python==3.9.*
  - pip
  - pip:
      - -c .constraints/py3.9.txt -e .[dev]
variables:
  PRETTIER_LEGACY_CLI: "1"
  PYTHONHASHSEED: 0
