name: ampform-dpd
channels:
  - defaults
dependencies:
  - graphviz
  - python==3.8.*
  - pip
  - pip:
      - |
        -c .constraints/py3.8.txt
        -e .[dev]
variables:
  PRETTIER_LEGACY_CLI: "1"
  PYTHONHASHSEED: 0
