name: Documentation
env:
  PYTHONHASHSEED: "0"

on:
  push:
    branches:
      - main
      - epic/*
  pull_request:
    branches:
      - main
      - epic/*
  workflow_dispatch:

jobs:
  documentation:
    uses: ComPWA/actions/.github/workflows/ci-docs.yml@linkcheck
    with:
      gh-pages: true
