name: pre-commit

on:
  push:
    branches:
      - main
      - epic/*
  pull_request:
    branches:
      - main
      - epic/*

jobs:
  style:
    name: Style checks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -c .constraints/py3.8.txt -e .[sty]
      - name: Run pre-commit hooks that don't work on pre-commit.ci
        run: |
          pre-commit run pyright -a --color always
