name: pytest

on:
  push:
    branches:
      - main
      - epic/*
  pull_request:
    branches:
      - main
      - epic/*
  workflow_dispatch:

jobs:
  codecov:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        python-version:
          - "3.7"
    uses: ComPWA/actions/.github/workflows/codecov.yml@linkcheck
    with:
      python-version: ${{ matrix.python-version }}
      runs-on: ${{ matrix.os }}
      package-name: ampform_dpd

  pytest:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        exclude:
          - os: ubuntu-20.04 # coverage job
            python-version: "3.7"
    uses: ComPWA/actions/.github/workflows/pytest.yml@linkcheck
    with:
      python-version: ${{ matrix.python-version }}
      runs-on: ${{ matrix.os }}
