name: CI
env:
  PYTHONHASHSEED: "0"

on:
  push:
    branches:
      - main
      - epic/*
  pull_request:
    branches:
      - main
      - epic/*
  workflow_dispatch:

jobs:
  doc:
    uses: ComPWA/actions/.github/workflows/ci-docs.yml@linkcheck
    with:
      gh-pages: true

  style:
    uses: ComPWA/actions/.github/workflows/ci-style.yml@linkcheck
    with:
      hooks: |
        editorconfig-checker
        pyright

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        exclude:
          - os: ubuntu-20.04
            python-version: "3.7"
        include:
          - coverage-target: ampform_dpd
            os: ubuntu-20.04
            python-version: "3.7"
    uses: ComPWA/actions/.github/workflows/pytest.yml@linkcheck
    with:
      python-version: ${{ matrix.python-version }}
      runs-on: ${{ matrix.os }}
