name: CI
env:
  PYTHONHASHSEED: "0"

on:
  push:
    branches:
      - main
      - epic/*
  pull_request:
    branches:
      - main
      - epic/*
  workflow_dispatch:

jobs:
  doc:
    uses: ComPWA/actions/.github/workflows/ci-docs.yml@linkcheck
    with:
      gh-pages: true

  codecov:
    uses: ComPWA/actions/.github/workflows/pytest.yml@linkcheck
    with:
      python-version: "3.7"
      runs-on: ubuntu-20.04

  pytest:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        exclude:
          - os: ubuntu-20.04 # coverage job
            python-version: "3.7"
    uses: ComPWA/actions/.github/workflows/pytest.yml@linkcheck
    with:
      python-version: ${{ matrix.python-version }}
      runs-on: ${{ matrix.os }}

  style:
    name: Style checks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          key: |
            ${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-${{ hashFiles('.constraints/py3.*.txt', '.pre-commit-config.yaml') }}
          path: |
            ~/.cache/pip/
            ~/.cache/pre-commit/
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -c .constraints/py3.8.txt -e .[sty]
      - name: Run pre-commit hooks that don't work on pre-commit.ci
        run: |-
          pre-commit run editorconfig-checker -a --color always
          pre-commit run pyright -a --color always
