name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONHASHSEED: "0"

on:
  push:
    branches:
      - main
      - epic/*
  pull_request:
    branches:
      - main
      - epic/*
  workflow_dispatch:

jobs:
  doc:
    uses: ComPWA/actions/.github/workflows/ci-docs.yml@linkcheck
    with:
      gh-pages: true

  style:
    uses: ComPWA/actions/.github/workflows/pre-commit.yml@linkcheck
    with:
      hooks: >-
        editorconfig-checker
        pyright

  pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
        include:
          - coverage-target: ampform_dpd
            python-version: "3.7"
    uses: ComPWA/actions/.github/workflows/pytest.yml@linkcheck
    with:
      python-version: ${{ matrix.python-version }}
      runs-on: ubuntu-22.04
