name: Linkcheck

on:
  push:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  pull_request:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  workflow_dispatch:

jobs:
  check_links:
    uses: ComPWA/actions/.github/workflows/linkcheck.yml@linkcheck
